# Generated by Django 3.2.7 on 2021-09-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='update',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
